### PR TITLE
Allow the user to hide entity fields

### PR DESCRIPTION
**Pull request by K-Phoen**
Can be useful for large graphs.

### CODE REVIEW

**Comment by OskarStark** [comment]
:+1:  like your PR

**Comment by jverdeyen** [comment]
:+1:

**Comment by OskarStark** [comment]
could you please add a test @K-Phoen

**Comment by K-Phoen** [comment]
I don't use this bundle anymore, it's been 11 months since I submitted this PR and there are no tests at all right now.

For these reasons, I don't feel like writing tests for my commit, sorry.

**Comment by alexandresalome** [comment]
Damnit, how could I have missed this feature for two years!

Well, just need to update README and CHANGELOG, also add yourself to the CONTRIBUTORS file and should run fine :)

Thanks and sorry for 2 years delay, I promise I'll be faster next time.

**Pull request closed without merging**
