### PR TITLE
Use newer php versions in Travis and run on lowest vendor code

### PR DESCRIPTION
**Pull request by gisostallenberg**

### CODE REVIEW

**Comment by gisostallenberg** [comment]
@alexandresalome Your take on "ho, let's merge all PRs and release them as quick as possible" seems to be needed one more time :wink:

**Comment by gisostallenberg** [comment]
Also see #17

**Comment by alexandresalome** [comment]
It's also the "congratulations, you are now a collaborator of the project" day :)

I really appreciate your effort to make this old bundle an up to date project

**Comment by gisostallenberg** [comment]
:smile: Thank you!

**Review by alexandresalome — APPROVED** [review]

**Comment by alexandresalome** [comment]
I let you merge when you feel ready.

**Comment by gisostallenberg** [comment]
image
I do not seem to be able to do so

**Comment by alexandresalome** [comment]
@gisostallenberg you have an invitation, somewhere, to accept. Maybe in your mails?

**Comment by gisostallenberg** [comment]
Thanks @alexandresalome for your support!

**Pull request merged**
