### PR TITLE
Run the command without being ContainerAware

### PR DESCRIPTION
**Pull request by gisostallenberg**
The ContainerAwareCommand is currently removed from Symfony and is not needed to run this command.

### CODE REVIEW

**Comment by gisostallenberg** [comment]
Also see #15

**Comment by gisostallenberg** [comment]
@alexandresalome would you be so nice to also look into this PR and release it when possible? Thank you so much.

**Comment by alexandresalome** [comment]
You're lucky, it's the "ho, let's merge all PRs and release them as quick as possible" day :-)

**Comment by gisostallenberg** [comment]
> You're lucky, it's the "ho, let's merge all PRs and release them as quick as possible" day :-)

Nice :tada: 
I think I should take advantage of that :stuck_out_tongue:

**Pull request merged**
